# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='fotos/person-flat.png', upload_to='fotos/')),
                ('titulo', models.CharField(default=' ', max_length=250, verbose_name='t\xedtulo')),
                ('subtitulo', models.CharField(default=' ', max_length=250, verbose_name='subt\xedtulo')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
            managers=[
                ('artigo', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='fotos/person-flat.png', upload_to='fotos/')),
                ('titulo', models.CharField(default=' ', max_length=250, verbose_name='t\xedtulo')),
                ('texto', models.CharField(default=' ', max_length=250, verbose_name='texto')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Artigo')),
            ],
            options={
                'verbose_name': 'Paragrafo',
                'verbose_name_plural': 'Paragrafos',
            },
            managers=[
                ('p', django.db.models.manager.Manager()),
            ],
        ),
    ]
